config/routes.rb
Rails.application.routes.draw do

  resources :event_job_period_associations
  resources :event_job_job_associations
  resources :events
  resources :jobs
  resources :periods
  resources :job_job_associations
  resources :users
  resources :microposts,          only: [:create, :destroy]

  post 'periods/change', as: :change_periods
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'

  get 'home'       => 'static_pages#home'
  get 'support'    => 'static_pages#support'
  get 'about'      => 'static_pages#about'
  get 'contact'    => 'static_pages#contact'
  get 'tcpsp'      => 'static_pages#tcpsp'
  get 'signup'     => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  post 'event_job_jobs/read_and_show_ofv', :to => 'event_job_job_associations#read_and_show_ofv'
  post 'event_job_jobs/read_optimization_results', :to => 'event_job_job_associations#read_optimization_results'
  post 'event_job_jobs/optimize', :to => 'event_job_job_associations#optimize'
  post 'event_job_jobs/delete_old_plan', :to => 'event_job_job_associations#delete_old_plan'

end

app/models/period.rb
class Period < ActiveRecord::Base
  has_many :events, through: :event_job_period_associations
  has_many :jobs, through: :event_job_period_associations
  has_many :event_job_period_associations, dependent: :destroy
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  before_action :set_period, only: [:show, :edit, :update, :destroy]

  # GET /periods
  # GET /periods.json
  def index
    @periods = Period.all
    @number_of_periods = Period.count
    if @mynumber_of_periods = nil
      @mynumber_of_periods=@number_of_periods
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @periods }
    end
  end


  def change
    @mynumber_of_periods = params[:mynewnumber].to_i
    @number_of_periods = Period.count
    number_of_missing_periods=@mynumber_of_periods - @number_of_periods

    if number_of_missing_periods > 0
      @events=Event.all
      @jobs=Job.all
      (1..number_of_missing_periods).each do |number|
        name="t#{number+@number_of_periods}"
        @new_period=Period.create!(name: name)
        @events.each { |eve|
          @jobs.each { |job|
            EventJobPeriodAssociation.create(event_id:eve.id, job_id: job.id, period_id: @new_period.id)
          }}
      end
    end

    if number_of_missing_periods < 0
      (@mynumber_of_periods +1 ..@number_of_periods).each do |number|
        name="t#{number}"
        Period.find_by_name(name).destroy
      end
    end

    @periods = Period.all
    render :template => "periods/index"
  end



  # GET /periods/1
  # GET /periods/1.json
  def show
  end

  # GET /periods/new
  def new
    @period = Period.new
  end

  # GET /periods/1/edit
  def edit
  end

  # POST /periods
  # POST /periods.json
  def create
    @period = Period.new(period_params)

    respond_to do |format|
      if @period.save
        format.html { redirect_to @period, notice: 'Period was successfully created.' }
        format.json { render :show, status: :created, location: @period }
      else
        format.html { render :new }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /periods/1
  # PATCH/PUT /periods/1.json
  def update
    respond_to do |format|
      if @period.update(period_params)
        format.html { redirect_to @period, notice: 'Period was successfully updated.' }
        format.json { render :show, status: :ok, location: @period }
      else
        format.html { render :edit }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /periods/1
  # DELETE /periods/1.json
 # def destroy
  #  @period.destroy
   # respond_to do |format|
   #   format.html { redirect_to periods_url, notice: 'Period was successfully destroyed.' }
   #   format.json { head :no_content }
    #  end
  #end



  private
  # Use callbacks to share common setup or constraints between actions.
  def set_period
    @period = Period.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def period_params
    params.require(:period).permit(:name, :add_cappa)
  end
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/views/periods/_form.html.erb
<%= form_for(@period) do |f| %>
  <% if @period.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@period.errors.count, "error") %> prohibited this period from being saved:</h2>

      <ul>
      <% @period.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Periode' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label 'Zusätzliche Kapazität' %><br>
    <%= f.number_field :add_cappa %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/periods/edit.html.erb
<h1>Editing Period</h1>

<%= render 'form' %>

<%= link_to 'Show', @period %> |
<%= link_to 'Back', periods_path %>

app/views/periods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Periods</h1>

<table id="periods" class="display">
  <thead>
    <tr>
      <th>Periode</th>
      <th>Zusätzliche Kapazität</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @periods.each do |period| %>
      <tr>
        <td><%= period.name %></td>
        <td><%= period.add_cappa %></td>
        <td><%= link_to 'Show', period %></td>
        <td><%= link_to 'Edit', edit_period_path(period) %></td>
        <td><%= link_to 'Destroy', period, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p>
  <b>Anzahl Perioden:</b>
  <%= @number_of_periods %>
</p>


<%= form_tag change_periods_path %>
<div class="field">
  <%= label_tag :mynewnumber, "Meine neue Anzahl von Perioden" %>
  <%= text_field_tag :mynewnumber, @mynumber_of_periods  %>
</div>
<%= submit_tag "Anzahl Perioden anpassen" %>


<% if @objective_function_value!=nil %>
    Die Kosten betragen <%=   @objective_function_value %> Geldeinheiten!   <br>   <br>
<% end %>

<%= link_to 'New Period', new_period_path %>
<br>
<br>
<%= link_to 'Zurück zur Verwaltung der Events', tcpsp_path %>

app/views/periods/new.html.erb
<h1>New Period</h1>

<%= render 'form' %>

<%= link_to 'Back', periods_path %>

app/views/periods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= best_in_place @period, :name %>
</p>

<p>
  <strong>Zusätzliche Kapazität</strong>
  <%= best_in_place @period, :add_cappa %>
</p>

<%= link_to 'Edit', edit_period_path(@period) %> |
<%= link_to 'Back', periods_path %>
<br>
<br>
<%= link_to 'Zurück zur Verwaltung der Events', tcpsp_path %>