config/routes.rb
Rails.application.routes.draw do

  resources :event_job_period_associations
  resources :event_job_job_associations
  resources :events
  resources :jobs
  resources :periods
  resources :job_job_associations
  resources :users
  resources :microposts,          only: [:create, :destroy]

  post 'periods/change', as: :change_periods
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'

  get 'home'       => 'static_pages#home'
  get 'support'    => 'static_pages#support'
  get 'about'      => 'static_pages#about'
  get 'contact'    => 'static_pages#contact'
  get 'tcpsp'      => 'static_pages#tcpsp'
  get 'signup'     => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  post 'event_job_jobs/read_and_show_ofv', :to => 'event_job_job_associations#read_and_show_ofv'
  post 'event_job_jobs/read_optimization_results', :to => 'event_job_job_associations#read_optimization_results'
  post 'event_job_jobs/optimize', :to => 'event_job_job_associations#optimize'
  post 'event_job_jobs/delete_old_plan', :to => 'event_job_job_associations#delete_old_plan'

end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :job_job_associations, foreign_key: "successor_id", :dependent => :destroy
  has_many :reverse_job_associations, foreign_key: "predecessor_id", class_name: "JobJobAssociation", :dependent => :destroy
  has_many :successors, through: :job_job_associations, source: :successor_id
  has_many :predecessors, through: :reverse_job_associations, source: :predecessor_id

  has_many :events, through: :event_job_period_associations
  has_many :periods, through: :event_job_period_associations

  has_many :event_job_job_associations, foreign_key: "successor_id", :dependent => :destroy
  has_many :event_reverse_job_associations, foreign_key: "predecessor_id", class_name: "EventJobJobAssociation", :dependent => :destroy
  has_many :successors, through: :event_job_job_associations, source: :successor_id
  has_many :predecessors, through: :event_reverse_job_associations, source: :predecessor_id
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :processing_time, :ressource_demand)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :processing_time %><br>
    <%= f.text_field :processing_time %>
  </div>
  <div class="field">
    <%= f.label :ressource_demand %><br>
    <%= f.number_field :ressource_demand %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jobs</h1>

<table id="jobs" class="display">
  <thead>
    <tr>
      <th>Vorgang</th>
      <th>Bearbeitungsdauer</th>
      <th>Kapazitätenbedarf</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.name %></td>
        <td><%= job.processing_time %></td>
        <td><%= job.ressource_demand %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>
<br>
<br>
<%= link_to 'Zurück zur Verwaltung der Events', tcpsp_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>
<br>
<br>
<%= link_to 'Zurück zur Verwaltung der Events', tcpsp_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= best_in_place @job, :name %>
</p>

<p>
  <strong>Processing time:</strong>
  <%= best_in_place @job, :processing_time %>
</p>

<p>
  <strong>Ressource demand:</strong>
  <%= best_in_place @job, :ressource_demand %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>
<br>
<br>
<%= link_to 'Zurück zur Verwaltung der Events', tcpsp_path %>